name       : libgtksourceview2
version    : 2.10.5
release    : 1
source     :
    - https://download.gnome.org/sources/gtksourceview/2.10/gtksourceview-2.10.5.tar.gz : f5c3dda83d69c8746da78c1434585169dd8de1eecf2a6bcdda0d9925bf857c97
license    : GPL-2.0
component  : desktop.gnome.core
summary    : Syntax highlighting text editing library for GTK 2.x
description: |
     GtkSourceView is a text widget that extends the standard GTK+ 2.x text widget GtkTextView. It improves GtkTextView by implementing syntax highlighting and
     other features typical of a source editor.
builddeps  :
    - pkgconfig(gtk+-2.0)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install